# Dados

In [41]:
dados <- data.frame(VD=c(26,16,19,16,13,    18,21,18,11,21,
                         20,12,16,25,13,    15,15,22,14,17,    
                         10,24,17,17,14),
                    F1=factor(c("A","B","C","D","E",  "B","C","D","E","A",
                                "C","D","E","A","B",  "D","E","A","B","C",
                                "E","A","B","C","D")),
                    B1=factor(c("a","b","c","d","e",  "c","d","e","a","b",
                                "e","a","b","c","d",  "b","c","d","e","a",
                                "d","e","a","b","c")),
                    B2=gl(5,5), B3=gl(5,1,25))

In [42]:
head(dados)

VD F1 B1 B2 B3
1 26 A  a  1  1 
2 16 B  b  1  2 
3 19 C  c  1  3 
4 16 D  d  1  4 
5 13 E  e  1  5 
6 18 B  c  2  1

In [43]:
sapply(dados,class)

VD        F1        B1        B2        B3 
"numeric"  "factor"  "factor"  "factor"  "factor"

In [44]:
matrix(dados$F1, 5,5)

[,1] [,2] [,3] [,4] [,5]
[1,] A    B    C    D    E   
[2,] B    C    D    E    A   
[3,] C    D    E    A    B   
[4,] D    E    A    B    C   
[5,] E    A    B    C    D

In [45]:
matrix(dados$B1, 5,5)

[,1] [,2] [,3] [,4] [,5]
[1,] a    c    e    b    d   
[2,] b    d    a    c    e   
[3,] c    e    b    d    a   
[4,] d    a    c    e    b   
[5,] e    b    d    a    c

In [46]:
matrix(dados$VD, 5,5)

[,1] [,2] [,3] [,4] [,5]
[1,] 26   18   20   15   10  
[2,] 16   21   12   15   24  
[3,] 19   18   16   22   17  
[4,] 16   11   25   14   17  
[5,] 13   21   13   17   14

## Modelo sem blocos

In [47]:
m1 <- lm(VD ~ F1, dados)
anova(m1)

Df Sum Sq Mean Sq F value  Pr(>F)      
F1         4 342.8  85.70   18.39056 1.765407e-06
Residuals 20  93.2   4.66         NA           NA

## Blocos ao acaso (paramétrico)

In [48]:
m1_ba <- lm(VD ~ F1 + B1, dados)
anova(m1_ba)

Df Sum Sq Mean Sq F value   Pr(>F)      
F1         4 342.8  85.700  16.886700 1.351205e-05
B1         4  12.0   3.000   0.591133 6.739476e-01
Residuals 16  81.2   5.075         NA           NA

# Blocos ao acaso (não-paramétrico)

In [28]:
install.packages('agricolae')

Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)


In [35]:
library(agricolae) 
data(grass) 
out<-with(chemical,friedman(B1,F1, VD,alpha=0.05, group=TRUE,console=TRUE, main="Data of the book of Conover")) 
#startgraph 
plot(out,variation="IQR") 
#endgraph



Study: Data of the book of Conover 

F1,  Sum of the ranks

    VD r
A 25.0 5
B 13.0 5
C 19.5 5
D 10.0 5
E  7.5 5

Friedman's Test
Adjusted for ties
Critical Value: 16.77551
P.Value Chisq: 0.002137007
F Value: 20.81013
P.Value F: 3.519767e-06 

Post Hoc Analysis

Alpha: 0.05 ; DF Error: 16
t-Student: 2.119905
LSD: 4.710533 

Treatments with the same letter are not significantly different.

  Sum of ranks groups
A         25.0      a
C         19.5      b
B         13.0      c
D         10.0     cd
E          7.5      d


## Quadrado latino

In [37]:
m1_ql <- lm(VD ~ F1 + B1 + B2, chemical)
anova(m1_ql)

Df Sum Sq Mean Sq   F value    Pr(>F)      
F1         4 342.8  85.700000 14.4438202 0.0001544241
B1         4  12.0   3.000000  0.5056180 0.7326699755
B2         4  10.0   2.500000  0.4213483 0.7903554527
Residuals 12  71.2   5.933333         NA           NA

### Quadrado greco-latino

In [38]:
m1_qgl <- lm(VD ~ F1 + B1 + B2 + B3, chemical)
anova(m1_qgl)

Df Sum Sq Mean Sq F value    Pr(>F)      
F1        4  342.8  85.70   14.6495726 0.0009410197
B1        4   12.0   3.00    0.5128205 0.7289001416
B2        4   10.0   2.50    0.4273504 0.7854473722
B3        4   24.4   6.10    1.0427350 0.4425434186
Residuals 8   46.8   5.85           NA           NA